/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.commons.lang3.StringUtils;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(StringUtils.reverse("Hello, World!"));
    }
}
